query getDiscussionsByCategory(
  $owner: String!
  $repo: String!
  $categoryId: ID!
  $cursor: String
) {
  repository(owner: $owner, name: $repo) {
    discussions(categoryId: $categoryId, first: 20, after: $cursor) {
      totalCount
      nodes {
        title
        body
        url
        bodyText
        number
        createdAt
        updatedAt
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
