query getDiscussionByNumber($owner: String!, $repo: String!, $num: Int!) {
  repository(owner: $owner, name: $repo) {
    discussion(number: $num) {
      title
      body
      url
      bodyText
      number
      createdAt
      updatedAt
    }
  }
}
