[about]
name = "TOMIKAWA Sotaro"
nickname = "ssssota"
github = "ssssota"
twitter = "ssssotaro"

[[careers]]
name = "豊田工業高等専門学校"
link = "https://www.toyota-ct.ac.jp/"
from = {year = 2015, month = 4}
to = {year = 2020, month = 3}
description = """
吹奏楽部に精を出した5年間(2年次に低学年代表、4年次にマネージャー)。楽器はホルン。

4年次の学祭では学科の展示としてUnityでモーショントラッキングを用いたレースゲームを主導。
"""

[[careers]]
name = "九州工業大学"
link = "https://www.kyutech.ac.jp/"
from = {year = 2020, month = 4}
to = {year = 2022, month = 3}
description = """
技術的な遅れを取り戻すため進学(編入)。
"""

[[careers]]
name = "デンキヤギ株式会社(インターン)"
link = "https://www.denkiyagi.jp/"
from = {year = 2018, month = 8}
to = {year = 2018, month = 9}
description = """
WebRTC技術を用いたトンネリングアプリの技術検証。
"""

[[careers]]
name = "デンキヤギ株式会社(アルバイト)"
link = "https://www.denkiyagi.jp/"
from = {year = 2020, month = 3}
to = {year = 2022, month = 3}
description = """
AzureやGraphQL、テキスト正規化など多岐にわたる技術検証。
言語としてHaxe/JSを用いた。
"""

[[careers]]
name = "楽天(インターン)"
link = "https://commerce-engineer.rakuten.careers/careers/graduates/internship/summer-short"
from = {year = 2020, month = 9}
to = {year = 2020, month = 9}
description = """
6名程度のチームによるハッカソン形式のインターン。

チャットやボイスチャット、時間記録などの機能を持ったバーチャルコワーキングスペースを作成・優勝。
フロントエンドを主導。
"""

[[careers]]
name = "株式会社nanoFreaks(業務委託)"
link = "https://nanofreaks.jp/"
from = {year = 2020, month = 12}
to = {year = 2021, month = 7}
description = """
水難救助ネットワークシステムの開発を行っているスタートアップ。

Firebaseを用いていたシステムをAWSにリプレイスするプロジェクトを始動、
インフラ、バックエンド、モバイルアプリなどを担当。
"""

[[careers]]
name = "株式会社ZOZO"
link = "https://corp.zozo.com/"
from = {year = 2022, month = 4}
description = """
新卒入社
"""

[[works]]
name = "fontvuer"
link = "https://github.com/ssssota/fontvuer/"
description = """
Electronを用いて作られたクロスプラットフォーム動作のフォント一覧表示アプリ。

任意のテキストでインストールされたフォントを表示できる。
"""

[[works]]
name = "svg2png-wasm"
link = "https://zenn.dev/ssssota/articles/svg2png-wasm"
description = """
SVG画像をPNGに変換するnpmライブラリ。

Rust製のライブラリをWebAssemblyにし、使いやすくした。
"""

[[skills]]
name = "TypeScript"
value = 4.5

[[skills]]
name = "JavaScript"
value = 4.5

[[skills]]
name = "Svelte"
value = 4

[[skills]]
name = "React"
value = 3.5

[[skills]]
name = "Rust"
value = 3

[[skills]]
name = "Flutter(Dart)"
value = 2

[[skills]]
name = "Docker"
value = 2
