on:
  pull_request:
    branches: [main]

jobs:
  deploy-to-stg:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      issues: write # for comment
      pull-requests: write # for comment
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Build svelte
        run: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx wrangler pages deploy build --project-name stg-ssssota | tee deploy.log
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: require('fs')
                .readFileSync('deploy.log', 'utf8')
                .split('\n')
                .reduce((acc, cur) => (cur.trim() === '' ? acc : cur))
            });
