on:
  pull_request:
    branches: [main]

jobs:
  deploy-to-stg:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: Build svelte
        run: pnpm build
      - run: npx wrangler pages publish build --project-name stg-ssssota
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
